import pyautogui
import time
import pyperclip  # For clipboard handling
import subprocess

time.sleep(2)

pyautogui.click(585, 82)
time.sleep(0.5)
pyautogui.write('about:config')
time.sleep(0.5)
pyautogui.press('enter')
time.sleep(3)
pyautogui.press('enter')
time.sleep(3)
pyautogui.write('privacy.resistFingerprinting')
time.sleep(0.5)
pyautogui.press('enter')
time.sleep(2)
pyautogui.click(1299, 231)
time.sleep(2.5)
pyautogui.hotkey('ctrl', 't')
time.sleep(1)
pyautogui.click(252, 42)
time.sleep(1.5)
pyautogui.click(585, 82)
time.sleep(0.5)
pyautogui.write('https://addons.mozilla.org/en-GB/firefox/addon/canvasblocker/')
time.sleep(0.5)
pyautogui.press('enter')
time.sleep(8)
pyautogui.click(760, 548)
time.sleep(4.7)
pyautogui.click(1200, 328)
time.sleep(3.7)
pyautogui.click(968, 191)
time.sleep(2.7)
pyautogui.click(1323, 234)
time.sleep(2.7)
pyautogui.hotkey('ctrl', 'w')
time.sleep(1.7)
pyautogui.hotkey('ctrl', 't')
time.sleep(1)
pyautogui.click(252, 42)
time.sleep(1.5)

